image: lab.wtfteam.pro:4567/containers/golangci-lint

variables:
  APP_PATH: develop.pztrn.name/gonews
  APP_NAME: gonews

stages:
  - test

before_script:
  - go version
  - golangci-lint --version
  - mkdir -p $GOPATH/src/$APP_PATH/$APP_NAME
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$APP_PATH/$APP_NAME
  - cd $GOPATH/src/$APP_PATH/$APP_NAME

lint:
  stage: test
  tags:
    - docker
  script:
    - pwd
    - ls -la
    - golangci-lint linters
    - golangci-lint run

test:
  stage: test
  tags:
    - docker
  script:
    - pwd
    - ls -la
    - go test -test.v -cover ./...