run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    # Actually not really needed.
    - gochecknoglobals
    # Well, it might help, but not so much.
    - funlen
linters-settings:
  lll:
    line-length: 420
  gocyclo:
    min-complexity: 40